# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/python-3.7.6-on-linux_64, last modified Wed Jan  8 19:02:45 2020
# ------------------------------------------------

package:
    name: python
    version: 3.7.6
source:
    -   md5: c08fbee72ad5c2c95b0f4e44bf6fd72c
        patches:
            - patches/0001-Add-Anaconda-Distribution-version-logic.patch
            - patches/0002-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - patches/0003-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - patches/0004-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - patches/0005-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - patches/0006-Support-cross-compiling-byte-code.patch
            - patches/0007-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - patches/0008-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - patches/0010-Win32-Do-not-download-externals.patch
            - patches/0011-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
            - patches/0014-Fix-cross-compilation-on-Debian-based-distros.patch
            - patches/0015-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
            - patches/0016-Unvendor-openssl.patch
            - patches/0017-Unvendor-sqlite3.patch
            - patches/0018-venv-Revert-a-change-from-https-github.com-python-cp.patch
            - patches/0019-Add-CondaEcosystemModifyDllSearchPath.patch
            - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
        url: https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tar.xz
build:
    detect_binary_files_with_prefix: true
    ignore_run_exports:
        - bzip2
        - libgcc-ng
    number: '2'
    string: h0371630_2
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuuid-cos6-x86_64 2.17.2 h22b9525_0
        - libuuid-devel-cos6-x86_64 2.17.2 0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - make 4.2.1 h1bed415_1
        - patch 2.7.6 h7b6447c_1001
        - pkg-config 0.29.2 h1bed415_8
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2019.11.27 0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - readline 7.0 h7b6447c_5
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - ld_impl_linux-64
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - ncurses >=6.1,<7.0a0
        - openssl >=1.1.1d,<1.1.2a
        - readline >=7.0,<8.0a0
        - sqlite >=3.30.1,<4.0a0
        - tk >=8.6.8,<8.7.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -V
        - python3 -V
        - 2to3 -h
        - pydoc -h
        - python3-config --help
        - python -c "import sys; files = [f for f in sys.argv[2:] if b' -partition=none'
            in open(f, 'rb').read()]; assert len(files) == 0, files" ${PREFIX}/lib/*/*.py
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
            python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
            if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
        - pushd tests
        - pushd distutils
        - python setup.py install -v -v
        - python -c "import foobar"
        - popd
        - pushd distutils.cext
        - python setup.py install -v -v
        - python -c "import greet; greet.greet('Python user')" | rg "Hello Python"
        - popd
        - pushd prefix-replacement
        - bash build-and-test.sh
        - popd
        - pushd cmake
        - cmake -GNinja -DPY_VER=3.7.6
        - popd
        - popd
    files:
        - tests/cmake/*
        - tests/cython/*
        - tests/distutils.cext/*
        - tests/distutils/*
        - tests/prefix-replacement/*
    requires:
        - cmake
        - cython
        - gcc_linux-64 7.3.0.*
        - gxx_linux-64 7.3.0.*
        - ninja
        - ripgrep
        - setuptools
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
