CI: azure
CONDA_BUILD_SYSROOT: /opt/MacOSX10.10.sdk
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- extend_keys
- pin_run_as_build
- ignore_build_only_deps
- ignore_version
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
libpng: 1.6.35
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libpng:
    max_pin: x.x
  xz:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
xz: '5.2'
zlib: '1.2'
