# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug  1 18:53:54 2019
# ------------------------------------------------

package:
    name: sox
    version: 14.4.2
source:
    md5: d04fba2d9245e661f245de0577f48a33
    url: http://sourceforge.net/projects/sox/files/sox/14.4.2/sox-14.4.2.tar.gz
build:
    detect_binary_files_with_prefix: true
    number: '1013'
    string: h27f72bc_1013
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - lame 3.100 h14c3975_1001
        - libgcc-ng 9.1.0 hdf63c60_0
        - libpng 1.6.35 h84994c4_1002
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mad 0.15.1b he1b5a44_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - lame >=3.100,<3.101.0a0
        - libgcc-ng >=7.3.0
        - libpng >=1.6.35,<1.7.0a0
        - libpng >=1.6.35,<1.7.0a0
        - mad >=0.15.1b,<0.16.0a0
        - xz >=5.2.4,<5.3.0a0
        - xz >=5.2.4,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -e $PREFIX/include/sox.h
        - test -e $PREFIX/lib/libsox.a
        - test -e $PREFIX/lib/libsox.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - sox --help |grep "FILE FORMATS" | grep mp3
about:
    home: http://sox.sourceforge.net/
    license: LGPLv2
    summary: A cross-platform command line utility that can convert various formats
        of computer audio files in to other formats.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - 183amir
        - alexbw
        - sdvillal
