# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug  1 16:19:53 2019
# ------------------------------------------------

package:
    name: mad
    version: 0.15.1b
source:
    patches:
        - mad.patch
    sha256: bbfac3ed6bfbc2823d3775ebb931087371e142bb0e9bb1bee51a76a6e0078690
    url: https://downloads.sourceforge.net/project/mad/libmad/0.15.1b/libmad-0.15.1b.tar.gz
build:
    number: '0'
    run_exports:
        - mad >=0.15.1b,<0.16.0a0
    string: he1b5a44_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h14c3975_2004
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - test -f $PREFIX/lib/libmad$SHLIB_EXT
about:
    description: "MAD is a high-quality MPEG audio decoder. It currently supports\
        \ MPEG-1 and the MPEG-2\nextension to lower sampling frequencies, as well\
        \ as the de facto MPEG 2.5 format.\nAll three audio layers \u2014 Layer I,\
        \ Layer II, and Layer III (i.e. MP3) \u2014 are fully implemented.\nMAD does\
        \ not yet support MPEG-2 multichannel audio (although it should be\nbackward\
        \ compatible with such streams) nor does it currently support AAC.\n"
    home: https://www.underbit.com/products/mad/
    license: GPL
    license_file: COPYING
    summary: High quality MPEG Audio Layer III (MP3) decoder
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - soumith
