CI: azure
c_compiler: '*'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: '*'
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '2.7'
python_abi_tag: cp37m
python_impl: cpython
python_impl_version: '3.7'
python_version: '3.7'
r_base: '3.5'
target_platform: linux-64
vc: '*'
zip_keys:
- - python_abi_tag
  - python_version
  - python_impl_version
  - python_impl
