# This file created by conda-build 3.18.12
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Mar  4 17:56:03 2020
# ------------------------------------------------

package:
    name: python_abi
    version: '3.7'
build:
    number: '1'
    string: 1_cp37m
requirements:
    run:
        - python 3.7.*
    run_constrained:
        - pypy <0a0
test:
    commands:
        - python --version
about:
    home: https://github.com/conda-forge/python_abi-feedstock
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Metapackage to select python implementation
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
