# This file created by conda-build 3.0.29
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/yaml-0.1.7-on-linux_64, last modified Mon Nov 13 21:42:02 2017
# ------------------------------------------------

package:
    name: yaml
    version: 0.1.7
source:
    patches:
        - CMakeLists.txt.patch
    sha256: 8088e457264a98ba451a90b8661fcb4f9d6f478f7265d48322a196cec2480729
    url: http://pyyaml.org/download/libyaml/yaml-0.1.7.tar.gz
build:
    number: '2'
    run_exports:
        - yaml >=0.1.7,<0.2.0a0
    string: had09818_2
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_11
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h4118e58_11
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libtool 2.4.6 h544aabb_3
        - pkg-config 0.29.2 hf7364cd_5
    run:
        - libgcc-ng 7.2.0.*
test:
    commands:
        - test -f "${PREFIX}/include/yaml.h"
        - test -f "${PREFIX}/lib/libyaml.a"
        - test -f "${PREFIX}/lib/libyaml.so"
about:
    description: 'YAML is a human friendly data serialization standard for all programming

        languages.

        '
    dev_url: https://github.com/yaml
    doc_source_url: https://github.com/yaml/www.yaml.org/tree/master/docs
    doc_url: http://www.yaml.org/spec/1.2/spec.html
    home: http://pyyaml.org/wiki/LibYAML
    license: MIT
    summary: A C library for parsing and emitting YAML.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - pelson
